# Generated by Django 2.1.2 on 2018-11-06 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contruction_name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('construction_items', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=15)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('task_name', models.CharField(max_length=30)),
                ('worker_number', models.IntegerField()),
                ('process', models.IntegerField()),
                ('content', models.TextField()),
                ('proposed_materials', models.TextField()),
                ('job_tomorrow', models.TextField(null=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submits', to='Construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='Construction.Project')),
            ],
        ),
        migrations.AddField(
            model_name='submit',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submits', to='Construction.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='submit',
            unique_together={('projects', 'team', 'date')},
        ),
    ]
