# Generated by Django 2.1 on 2018-11-07 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='Construction.Project'),
        ),
    ]
