# Generated by Django 2.1 on 2018-11-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0002_auto_20181107_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='investor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
